version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: ipvc
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/Users/ruicarvalho/Desktop/Trabalho_Servicos_Distribuidos/docker/volumes/postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ipvc@ipvc.pt
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/Users/ruicarvalho/Desktop/Trabalho_Servicos_Distribuidos/docker/volumes/postgres

volumes:
  local_pgdata:
  pgadmin-data:
